- README.md
- decoder.go
- rtsp.go
Unlike the [first PR](https://github.com/erh/viamrtsp/pull/1) which contains development packaging work, this aims to be the minimal change needed to add Codec Detection and H265 support. Build work can be introduced in subsequent PRs.
- This PR allows the module binary to handle both H264 and H265 codecs at runtime.
- If a given endpoint has tracks that support both codecs, H264 will take preference.
- Make sure FFmpeg deps are installed: 
`sudo apt install libswscale-dev libavcodec-dev libavformat-dev libavutil-dev`
- Build go binary: 
`make bin/viamrtsp`
- Run as "local" module on Linux machine with FFmpeg deps installed.
```
{
"executable_path": "/path/to/viamrtsp",
"name": "viamrtsp",
"type": "local"
}
```
- Configure component to listen to RTSP server endpoint.
```
{
"model": …
```
> RSDK-6814 - Add Codec Detection and H265 Support

- cmd/module/cmd.go
- cmd/remote/cmd.go
- decoder.go
- meta.json
- rtsp.go
https://viam.atlassian.net/browse/RSDK-7079
Adds `rtsp` model that streams from any available, supported codec
Makes `rtsp-h264` return error if detected codec is not h264
If we're adding a generic `rtsp` model, but also keeping `rtsp-h264`, should we add `rtsp-h265`? Plus more accordingly to new codecs we introduce?
Edit: I went ahead and added `rtsp-h265` as well— can remove it if bad
1. `h264` fake stream with model `rtsp`: Success ✅
2. `h264` fake stream with model `rtsp-h264`: Success ✅
3. `h264` fake stream with model `rtsp-h265`: `resource build error: rpc error: code = Unknown desc = h265 track not found` ✅
5. `h265` fake stream with model `rtsp`: Success ✅
6. `h265` fake stream with model `rtsp-h264`: `resource build error: rpc error: code = Unknown desc = h264 track not found` ✅ …
> [RSDK-7079] Refactor models

- .github/workflows/integration-test.yml
https://github.com/erh/viamrtsp/pull/7 depends on go 1.21 (which is the currently supported go version in RDK) 
This updates CI to use go 1.21 so that that PR can pass tests
> bump-go-version-to-1.21

- decoder.go
- rtsp.go
The goal of this PR is to remove the 20 byte filter from h264 decoder loop by properly flagging the decoder to expect partial frames. This is needed since we are feeding NALs into the decoder instead of by frame boundary.
- Tested that the decoder no longer logs `no frame!`.
- No regression to h264/h265 decoding performance or stability.
- [AV_CODEC_FLAG2_CHUNKS](https://ffmpeg.org/doxygen/2.8/group__lavc__core.html#gabc5592664ff0686def0c2b41cfcc322d)
> RSDK-7226 Add chunks flag to decoder

- .canon.yaml
- .github/workflows/integration-test.yml
- .gitignore
- Makefile
- README.md
Changes:
1. Update Makefile to support building concurrently for multiple platforms
1. Update .canon.yaml to have own unique names to prevent conflicting with rdk canon config & use same images as RDK
1. Add FFmpeg directory to .gitignore
1. Remove `make test` target as it didn't work (likely due to `CGO_LDFLAGS`). It is also unnecessary as `go test` works just fine when run outside of make
Manual Testing: (with vaim-server https://github.com/viamrobotics/rdk/releases/tag/v0.24.1)
- Change rtsp camera from outputting h264 -> h265 -> h264B -> H264H & confirm that the camera stream reconnects (does not apply for `erh:viamrtsp:rtsp-mjpeg`)
- for non  `erh:viamrtsp:rtsp` confirm that camera streams with the codec in their model name work & all others prevent them from booting
Models: …
> [RSDK-1155] remove build target conflicts

- decoder.go
- rtsp.go
Reverts https://github.com/erh/viamrtsp/pull/12/files due to it causing https://viam.atlassian.net/browse/RSDK-7346 / https://viam.atlassian.net/browse/RSDK-7354
This is a temp fix to revert back to `v0.0.1` behavior. @seanavery is working on a more long term fix
> revert-RSDK-7226

- rtsp.go
Changes:
1. Remove the verbose `SubscribeRTP|Unsubscribe Start|Stop` log added during debugging
2. Change to cancelFn rather than cancelCuaseFn as the cause is not needed.
> small-refactor: remove verbose logging & cancel cause

- decoder.go
This PR simply adds in a copy from the `dstFrame` in C memory to go bytes to avoid filling the go image with a pointer. The go garbage collector can now manage the lifetime of the frame data.
- Confirmed that toggling back and for between h264/h265 and triggering EOF no longer results in occasional segfaults ✅ 
- Here is an example log output toggling back and forth between h264/5,
- EOF hits but no longer segfaults.
```
6/6/2024, 1:39:08 PM error robot_server.modmanager.process.viamrtsp_/home/viam/viamrtsp-malloc-final.StdErr pexec/managed_process.go:280 \_ [swscaler @ 0x7f2c3a5640] No accelerated colorspace conversion found from yuv420p to rgba.
6/6/2024, 1:39:08 PM info robot_server.viamrtsp.rdk:component:camera/ip-cam1 host/rtsp.go:166 reconnected to rtsp server url: …
```
> RSDK-7325 - Fix for dangling pointer segfaults

- .github/workflows/quality-checks.yml
- Makefile
This fixes an issue on Darwin, where tests fail to pick up static FFmpeg build and rely on local homebrew installation instead. Added explicity `CGO_CFLAGS` setter since `PKG_CONFIG_PATH` was not linking correctly with go test 
commands.
Warning output:
```
cgo-gcc-prolog:180:11: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
/opt/homebrew/Cellar/ffmpeg/7.0/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
/opt/homebrew/Cellar/ffmpeg/7.0/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
cgo-gcc-prolog:180:11: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
/opt/homebrew/Cellar/ffmpeg/7.0/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been …
```
> RSDK-7330 - Make tests run against static FFmpeg build

- rtsp.go
This fixes the following output:
error decoding(1) h264 rstp stream %!w(*errors.errorString=&{invalid FU-A packet (non-starting)})
> Avoid the %w usage meant for wrapping errors with `fmt.Errorf`.

- .github/workflows/integration-test.yml
- LICENSE
- Makefile
- README.md
- cmd/module/cmd.go
- cmd/remote/cmd.go
- go.mod
- meta.json
- rtsp.go
https://viam.atlassian.net/browse/RSDK-8589
Something I want to make sure/clarify before merging and running `viam module update` with the new meta.json is how user configs will update from `erh:viamrtsp` to `viam:viamrtsp`
Do we need to run a migration?
Update: the answer is no, Michael Lee's logic includes old triplet -> new triplet redirection
> [RSDK-8589] erh -> viam

- .github/workflows/integration-test.yml
- .github/workflows/publish.yml
If we were to continue using #44 only, we would lose support for Bullseye. Buildjet arm runners use a newer version of glibc. We should use canon's antique profile. This will also better align our manual test builds with deployed builds.
Update: I added a condition that doesn't use canon for Android. For some reason android builds don't work in the canon docker antique environment. The current android build flow does not use Docker or canon
Tests:
["Successful" linux/arm64 CI run](https://github.com/viam-modules/viamrtsp/actions/runs/10854614809/job/30125433385?pr=48)
["Successful" android/arm64 CI run](https://github.com/viam-modules/viamrtsp/actions/runs/10854576184/job/30125308560)
["Successful" linux/amd64 CI run](https://github.com/viam-modules/viamrtsp/actions/runs/10852087675/job/30 …
> [RSDK-7953]   Consolidate build workflow for all archs part 2

- .github/workflows/integration-test.yml
- decoder.go
- pool.go
https://viam.atlassian.net/browse/RSDK-8667
> This ticket was created to address Dan’s comment [here](https://github.com/erh/viamrtsp/pull/41#discussion_r1719998891)
> 
> Proposed solution:
> 
> Add an extra conditional where we detect mismatch between dst and source yuv frame that checks if the dst frame already has a defined non-zero height and width (a reused frame). If there is a non-zero dimension mismatch between dst and source yuv, then we know the resolution has changed.
> 
> We should flush the pool (possibly re-seed) to prevent the case Dan outlined with a fast resolution switch.
> [RSDK-8667]   Fix possible edge case for decode wonkiness using pool clear func

- README.md
- rtsp.go
- rtsp_test.go
https://viam.atlassian.net/browse/RSDK-9228
Manual test (h264)
As you can see, it's not specified in the config, but in the logs it indicates rtp passthrough is happening
Also verified that setting the field true results in passthrough still happening, and setting the field to false results in passthrough not happening
> [RSDK-9228] Default RTPPassthrough to true and update README

- Makefile
- decoder.go
- mime.go
- mime_cgo.go
- mime_test.go
- rtsp.go
This PR moves to using libAV for JPEG mime handling and streamlines the frame pipeline from decoding to API returns from Image.
- Removes RGB pixel conversion in decoder.
- We now simply copy yuv420 bytes to the AvFrameWrapper in the pool. 
- Moves AvFrameWrapper toImage helper to fill Ycbcr image.
- Replaces golang jpeg encoder with libav MJPEG codec.
- Sets up an MJPEG encoder that will reinitiate on size changes.
- Makes the MJPEG decoder path more efficient by removing going to and from a go image.
- basic tests:
- h264 Image ✅ 
- h264 passthrough ✅ 
- h265 Image ✅ 
- mjpeg Image ✅ 
- frame size changes while running ✅ 
- two concurrent clients polling Image ✅ 
- reconfigure stuff:
- module reconfigure ✅ 
- viam-server shutdown does not hang ✅ 
- removing and adding module no hangs ✅ …
> [RSDK-9688, RSDK-9732, RSDK-9733] Use libav for JPEG encoding

- .github/workflows/integration-test.yml
https://viam.atlassian.net/browse/RSDK-9723
Noticed that `Non full-range YUV is non-standard` as per the error message attached by Nick on the Jira ticket
Changed requested pixel format from yuv420 to yuvj420 (full color range) for mjpeg and all CI successfully runs now
> [RSDK-9723] Fix mjpeg CI

- viamonvifdiscovery/service.go
I missed that the new discovery function still needs a credential to be passed in to run. by adding an empty credential it ensures that insecure cameras on the network are found
> add empty cred

- .github/workflows/integration-test.yml
- rtsp.go
Currently, the default behavior of gortsplib is to first try udp and then fallback to tcp if it is not available. This is an issue because the parser is much more stable when using TCP transport.
This is a simple PR to wrap our `reconnectClient` flow with a retry mechanism to attempt the connection using TCP, UDP, and UDP-multicast in a priority order.
!!! Due to a quirk with how Setup's are handled in gortsplib we cannot simply retry Setup calls with specified transport so we must fully teardown and restart the connection flow for each attempt.
Manual tested transport retries using mediamtx. 
We can specify available transports in the `mediamtx.yml` file and connect an appropriate fake RTSP feed using FFmpeg.
`protocols: [udp, multicast, tcp]`.
`ffmpeg -re -f lavfi -i …
> [RSDK-9833] - Add preference for TCP transport

- rtsp.go
If we get an inter-frame (TRAIL_N or other) that is spread across multiple NALUs, which happens with large frame sizes, the decoder runs into issues since it is expecting to send and receive payloads on frame boundaries. 
This PR simply always packs the AU into a single packed payload. This ensures our decoder is able to receive a frame on the other end.
Confirmed this works for inter-frames (TRAIL_N) as well as key frame sets (VPS, SPS, PPS, IDR_W_RADL). In other words, it is ok to pack no matter what.
- steves 4k cam ✅ 
- other random office cams ✅
> [RSDK-9834] - Pack NALUs in h265 decode flow

- mime.go
- mime_cgo.go
- mime_test.go
- rtsp.go
[RSDK-9807](https://viam.atlassian.net/browse/RSDK-9807)
[RSDK-9807]: https://viam.atlassian.net/browse/RSDK-9807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Tested with my local Python SDK client
```
async def main():
try:
robot = await connect()
cam = Camera.from_robot(robot, 'rtsp-1')
count = 0
while count < 3:
try:
count += 1
img = await cam.get_image(mime_type=CameraMimeType.VIAM_RGBA)
print(f"count: {count}")
print(f"img.mime_type: {img.mime_type}")
print(f"img.data: {img.data[:800]}")
pil_img = viam_to_pil_image(img)
pil_img.show()
except Exception as e:
print(f"Error getting/processing image: {e}")
break
finally:
await cam.close()
await robot.close()
```
This means that the serialized output was successfully sent over the wire and …
> [RSDK-9807]   Return RGBA bytes from viamrtsp

- rtsp.go
https://viam.atlassian.net/browse/RSDK-9920
1. Add new config parameter: `lazy_decode: bool`, default: false
2. Only applies if codec is h264. If set and codec is anything else, log a warning at startup.
3. If set to true, accumulate the NALUs (h264 messages) since the last IDR. Only compute an image from those NALUs when camera.Image is called.
**Hardware: Pi 5:**
> Resolution: 2304*1296 (larger than 1080p)
> Frame Rate (FPS): 25
> Max Bitrate (Kbps): 4096
> I-frame Interval: 2x (about every 2 seconds)
> 
**Baseline `lazy_decode: false` or unset:** 
1. no callers: htop reports ~35% cpu 
2. with gostream calling camera.Image as fast as it can:  htop reports ~50% cpu, each request takes ~35 ms
**`lazy_decode: true`**
1. no callers: htop reports ~2% cpu 
2. with gostream calling …
> [RSDK-9920] - add lazy_decode

- rtsp.go
[Ticket](https://viam.atlassian.net/browse/RSDK-9920)
Follow up from https://github.com/viam-modules/viamrtsp/pull/85
Manual Testing:
Camera: [Marquis IPC-XD400](https://marquis-store.com/products/hikvision-uniview-compatible-ip-turret-camera-4mp)
1. m2 macbook air 2022 + pi 5 + orin nx:
> codecs: H264, H265, H265+
> resolution: 2560x1440
> fps: 20
> bit rate: 3500(kb/s)
4k Camera[RLC-823A 16X](https://reolink.com/product/rlc-823a-16x/?srsltid=AfmBOoqr_vec3Dj5v1v33TSjdm1hzuaoAeIFoT7sIfE16IV8Nbb2eRi8)
> codecs: H265
> resolution: 3840*2160
> fps: 25
> bit rate: 4096 (kb/s)
> RSDK-9920-add-h265-lazy-decode

- Makefile
- decoder.go
- go.mod
- go.sum
- mime.go
- mime_cgo.go
- rtsp.go
1. Disables building android releases - this is b/c the android build requires not using cgo. Embeding viarmtsp into video-store requires cgo. Android builds of viamrtsp are not going to be able to have the video-store features. I'm haven't done the work to allow for both cgo (with video-store) and non cgo (without video-store) builds of viamrtsp. That will need to be done as a follow up.
2.  Allows the following config to enable video-store features:
```
{
"video_store": {
"size_gb" int,
"upload_path": int,
"storage_path": int
}
}
```
> RSDK-9919-move-video-store-logic-into-viamrtsp2

- rtsp.go
- rtsp_test.go
There is an issue where we are never releasing the `latestFrame` cache back to the pool during closeout. When the avFramePool closes out the latest frame never gets freed causing a lingering frame allocation.
- We can see that when properly releasing the frame we are now freeing more frames during closeout. See the following logs -- first log set is from upstream and the second is the feature branch.
- Manually verified memory usage with `top` does not increase from disabling and re-enabling viamrtsp component.
```
3/3/2025, 4:52:34 PM info rdk:component:camera/rtsp-cam-3     host/pool.go:112 Num pool frames remaining at close: 1   log_ts 2025-03-03T21:52:34.154Z
```
```
3/3/2025, 4:57:51 PM info rdk:component:camera/rtsp-cam-3     host/pool.go:112 Num pool frames remaining at close: 2   …
```
> [RSDK-10071] - Fix avFramePool memory leak

- go.mod
- go.sum
- viamonvif/discovery.go
- viamonvif/mdns_server.go
Demonstrated a `ping` worked for > 2 minutes after running a single discovery request. Added a camera via service discovery config copying.
```
dgottlieb@empanada:~/viam/robotConfigs $ for i in {1..80}; do date; ping -c 1 AMC1083EC3C8118218.local; sleep 60; done
Mon Mar 17 02:12:12 PM EDT 2025
PING AMC1083EC3C8118218.local (10.1.11.241) 56(84) bytes of data.
64 bytes from 10.1.11.241 (10.1.11.241): icmp_seq=1 ttl=64 time=3.32 ms
--- AMC1083EC3C8118218.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 3.320/3.320/3.320/0.000 ms
Mon Mar 17 02:13:12 PM EDT 2025
PING AMC1083EC3C8118218.local (10.1.11.241) 56(84) bytes of data.
64 bytes from 10.1.11.241 (10.1.11.241): icmp_seq=1 ttl=64 time=2.58 ms
--- AMC1083EC3C8118218.local ping …
```
> RSDK-10260: Use updated zeroconf that responds to plain mDNS questions.

- README.md
- meta.json
This is needed for it to be findable via app.viam.com and for the inline docs to work in app.viam.com's config ui.
> add-ptz-to-docs-and-meta-json

- .github/workflows/quality-test.yml
- viamonvif/service.go
- viamonvif/service_test.go
- Adds background worker to discover resources on an interval.
- `DiscoverResources` returns cached resources if available.
https://github.com/user-attachments/assets/613bb99c-293a-455e-b33b-b556a6348596
- DiscoverResources waits for results when queried shortly after boot up ✅ 
- DiscoverResources returns cached results immediately when available ✅ 
- DiscoverResource uses extra credentials when provided ✅ 
We do not have the infra test ONVIF in CI. See follow-up ticket [here](https://viam.atlassian.net/browse/RSDK-10970).
___ 
TODO:
For reference, here is how to repro IP change on an orin-nano:
1. Run mediamtx for RTSP server
2. Run fake ffmpeg cam
```
ffmpeg -f lavfi -re -i testsrc=size=800x600:rate=30 -vf drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:text='Timestamp …
```
> [CONSULT-1116] - Background discovery cache

- README.md
- go.mod
- go.sum
- videostore/config.go
- videostore/videostore.go
https://viam.atlassian.net/browse/RSDK-10750
To check this, I will screenshot htop before deleting `index.sqlite.db` and then screenshot htop after the deletion when the long index is happening.
Before^
A couple minutes after deleting the .db file^
It looks like nothing crazy is happening. No cores are being maxed out at 100% and the workload looks marginally higher.
This was tested implicitly in the above test by triggering the long index with a during-runtime delete of the .db file.
```
{
"command": "save",
"from": "2025-05-20_12-53-02",
"to": "2025-05-20_12-53-12",
"metadata": "metadata",
"async": false
}
```
https://github.com/user-attachments/assets/977d43a0-f492-4c00-b80a-398fbee3eae1
Nice!
Swapped dir from default .viam/video-storage to a custom dir. Verified the swap with a …
> [RSDK-10750] Update video-store and RDK dep to serve get-storage-state

- viamonvif/device/device.go
- viamonvif/discovery.go
Now that we are running discovery in a background loop if there are any onvif devices which don't recognize the credentials on the network, all of those will be reported as errors. 
This is inappropriate when only a subset of the devices on the network are intended to be used by the machine.
This reduces log spam.
These logs can be re-enabled by enabling module level debug logging.
> change-noisy-discovery-warn-logs-to-debug

- ptzclient/client.go
- viamonvif/device/device.go
- viamonvif/discovery.go
- viamonvif/discovery_test.go
- viamonvif/service.go
- viamonvif/xsd/onvif/onvif.go
This PR adds ptz-client resource configs to the `onvif` model `DiscoverResources` return.
- Reolilnk
- DiscoverResources returns ptz-client configs for each node_token ✅ 
- Component does not error out when added ✅ 
- `continuous-move` DoCommands work ✅ 
```json
{
"api": "rdk:component:generic",
"attributes": {
"address": "10.1.5.0:8000",
"discovery_dep": "discovery-1",
"movements": {
"continuous": {
"pan_tilt": {
"space": "VelocityGenericSpace",
"x_max": 1,
"x_min": -1,
"y_max": 1,
"y_min": -1
},
"zoom": {
"space": "VelocityGenericSpace",
"x_max": 1,
"x_min": -1
}
}
},
"password":  <pass>,
"profile_token": "000",
"ptz_node_token": "000",
"rtsp_address": "rtsp://<user>:<pass>@10.1.5.0:554/",
"username": <user>
},
"model": "viam:viamrtsp:onvif-ptz-client",
"name": …
```
> [RSDK-11088] - Add ptz-client discovery

- ptzclient/client.go
There is no guarantee that the onvif server for a ptz camera is authenticated, this PR simply removes username and password validation.
Tested that the following Amcrest camera ptz-client (which is unauthenticated but returns ptz profile) no longer errors out with empty username and password ✅ 
```
{
"api": "rdk:component:generic",
"attributes": {
"address": "EF00000005087E34.local",
"discovery_dep": "discovery-1",
"movements": {
"absolute": {
"pan_tilt": {
"space": "PositionGenericSpace",
"x_max": 1,
"x_min": -1,
"y_max": 1,
"y_min": -1
},
"zoom": {
"space": "PositionGenericSpace",
"x_max": 1,
"x_min": -1
}
},
"continuous": {
"pan_tilt": {
"space": "VelocityGenericSpace",
"x_max": 1,
"x_min": -1,
"y_max": 1,
"y_min": -1
},
"zoom": {
"space": "VelocityGenericSpace",
"x_max": 1,
"x_min": …
```
> Allow unauthenticated ptz clients
